baseURL = "https://www.lccs.ml"
languageCode = "jp"
title = "LCCreators"
theme = "luxen"
googleAnalytics = "G-ME0X82ZRX3"
[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://blog.lccs.ml"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

[build]
  writeStats = true