name = "Luxen"
license = "MIT"
licenselink = "https://github.com/opera7133/lcweb/blob/master/LICENSE"
description = ""
homepage = "https://www.lccs.ml"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "wamo"
  homepage = "https://wmsci.com"
